=== premierrt/boot_spring_integration_db_adapter/src/main/resources/schema_linki.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://rafal/types" targetNamespace="http://rafal/types"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.1.0">

<xsd:element name="uslugiLinki" type="uslugiLinkiType"/>


	<xsd:simpleType name="idType">
		<xsd:restriction base="xsd:long" />
	</xsd:simpleType>
	
	

	<xsd:complexType name="uslugiLinkiType">
		<xsd:sequence>
			<xsd:element minOccurs="0" maxOccurs="unbounded"
				name="uslugiLinki" type="uslugaLinkiType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="uslugaLinkiType">
		<xsd:sequence>
			<xsd:element name="powiazanie" type="powiazanie"
				maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="uslugaId" type="idType" use="required" />
	</xsd:complexType>

	<xsd:complexType name="powiazanie">
		<xsd:sequence>
			<xsd:element name="relacjaPowiazania" type="relacjaPowiazania"
				maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="statusFailedMessage" type="xsd:string"
			use="required" />
	</xsd:complexType>

	<xsd:complexType name="relacjaPowiazania">
		<xsd:attribute name="uslugaId" type="idType" use="required" />
		<xsd:attribute name="status" type="xsd:string" use="required" />
		<xsd:attribute name="operacja" type="operacjeType"></xsd:attribute>
		<xsd:attribute name="badel" type="xsd:boolean" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="operacjeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="AKTWYUJ"></xsd:enumeration>
			<xsd:enumeration value="DEAKTWYUJ"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="statusType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="AKTYWNY"></xsd:enumeration>
			<xsd:enumeration value="NIEAKTYWNY"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== premierrt/boot_spring_integration_db_adapter/src/main/resources/schema_linki_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:uslugiLinki xmlns:p="http://rafal/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rafal/types schema_linki.xsd ">
  
  
  <p:uslugiLinki uslugaId="10">
    <p:powiazanie statusFailedMessage="To jest zle powiazanie">
      <p:relacjaPowiazania badel="true"  status="AKTYWNY" uslugaId="20"/>
      <p:relacjaPowiazania badel="true"  status="AKTYWNY" uslugaId="30"/>
       <p:relacjaPowiazania badel="true" status="AKTYWNY" uslugaId="40"/>
    </p:powiazanie>
  </p:uslugiLinki>
  
  
    <p:uslugiLinki uslugaId="210">
    <p:powiazanie statusFailedMessage="To jest zle powiazanie 222 ">
      <p:relacjaPowiazania badel="true"  status="NIEAKTYWNY" uslugaId="220"/>
      <p:relacjaPowiazania badel="true"  status="AKTYWNY" uslugaId="230"/>
       <p:relacjaPowiazania badel="true"  status="AKTYWNY" uslugaId="240"/>
    </p:powiazanie>
  </p:uslugiLinki>
  
  
    <p:uslugiLinki uslugaId="310">
    <p:powiazanie statusFailedMessage="To jest zle powiazanie 3333">
      <p:relacjaPowiazania badel="true" operacja="DEAKTWYUJ" status="AKTYWNY" uslugaId="320"/>
      <p:relacjaPowiazania badel="true" operacja="DEAKTWYUJ" status="NIEAKTYWNY" uslugaId="330"/>
       <p:relacjaPowiazania badel="true" operacja="DEAKTWYUJ" status="AKTYWNY" uslugaId="340"/>
    </p:powiazanie>
  </p:uslugiLinki>
  
</p:uslugiLinki>
